services:
  - type: web
    name: seu-app-nodejs
    env: node
    plan: starter
    buildCommand: |
      apt-get update && apt-get install -y chromium
      npm install
    startCommand: node index.js
